#!/usr/bin/env python3

import sys

from libtrish import compare


if __name__ == '__main__':
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} fileA fileB")
        exit(1)
    print(compare(sys.argv[1], sys.argv[2]))
